title: birdf00t
description: 개발과 배움을 기록하는 공간
url: "https://birdf00t.github.io"
baseurl: ""

author: birdf00t

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
